name: PR Checks

on:
  pull_request:

env:
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  pr:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Enable Corepack (Yarn 4)
        run: corepack enable
      - name: Restore node_modules cache files
        uses: actions/cache@v5
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: node-modules-
      - run: yarn install --frozen-lockfile
      - name: Run lint
        run: 'yarn nx run-many --target lint --parallel=3'
      - name: Run test
        run: 'yarn nx run-many -t test --parallel=3'
      - name: Run build
        run: 'yarn nx run-many --target build --parallel=3'
      - name: Run e2e
        uses: cypress-io/github-action@v6
        with:
          command: yarn nx run-many -t e2e --parallel=1
        continue-on-error: true
